In [3]:
from pathlib import Path
for f in Path.cwd().iterdir():
    if "Gea" in f.name:
        print(f.name)

Revinate_reviews_export_Gea_2025_26.csv
Revinate_reviews_export_Gea_2023.csv
Revinate_reviews_export_Gea_2024.csv
Gea_Reviews_2022_2026_Combined.xlsx
Revinate_reviews_export_Gea_2022.csv
Gea_Data_Preprocessing_stage.ipynb

In [6]:
import pandas as pd

gea= pd.read_excel("Gea_Reviews_2022_2026_Combined.xlsx",
                  header=1)

print("Total Gea reviews:", len(gea))
print("\nColumns:")
print(gea.columns.tolist())

gea.head()

Total Gea reviews: 328

Columns:
['Hotel', 'Review Site', 'Revinate Collected Date', 'Review Date', 'Rating', 'Review Title', 'Review', 'Subrating: Cleanliness', 'Subrating: Location', 'Subrating: Rooms', 'Subrating: Service', 'Subrating: Value', 'Subrating: Sleep Quality', 'Recommended', 'Response', 'Review Link', 'Ticket', 'External ID', 'Language', 'Author', 'Author Location', 'Review ID', 'Response Submitted Date', 'Response Posted Date', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26']

,Hotel,Review Site,Revinate Collected Date,Review Date,Rating,Review Title,Review,Subrating: Cleanliness,Subrating: Location,Subrating: Rooms,...,External ID,Language,Author,Author Location,Review ID,Response Submitted Date,Response Posted Date,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,Katikies Santorini- Gea House,Priceline,12/01/22,12/01/22,4,Excellent.,Good: staff location Bad: we didn’t receiv...,NaN,NaN,NaN,...,LW0820,English,Shana,VG,1134445675,NaN,NaN,NaN,NaN,NaN
1,NaN,Expedia,11/13/22,11/12/22,5,NaN,Of course the views are to die for! Room was v...,5,NaN,NaN,...,LW0820,English,Denise,NaN,889302296,11/14/22,11/14/22,NaN,NaN,NaN
2,NaN,Ctrip,11/13/22,11/13/22,5,Outstanding,Of course the views are to die for! Room was v...,NaN,NaN,NaN,...,LW0820,English,Denise,NaN,973575188,NaN,07/26/24,NaN,NaN,NaN
3,NaN,Booking.com,11/01/22,11/01/22,5,exceptionnel,Good: vue incroyable piscine petit déjeuner,5,5,5,...,LW0820,French,Laetitia,France,885648720,11/01/22,11/02/22,NaN,NaN,NaN
4,NaN,NaN,10/28/22,10/28/22,5,NaN,NaN,5,5,5,...,LW0820,NaN,Lisa,United States of America,884883477,NaN,NaN,NaN,NaN,NaN

In [7]:
# Create Review_Text

gea["Review Title"] = gea["Review Title"].fillna("").astype(str)
gea["Review"] = gea["Review"].fillna("").astype(str)

gea["Review_Text"] = (
gea["Review Title"].str.strip() + " " +
gea["Review"].str.strip()
).str.strip()

print("Total reviews:", len(gea))
print("Missing Review_Text:", gea["Review_Text"].eq("").sum())

gea[["Review Site", "Review Title", "Review", "Review_Text"]].head(10)

Total reviews: 328
Missing Review_Text: 56

,Review Site,Review Title,Review,Review_Text
0,Priceline,Excellent.,Good: staff location Bad: we didn’t receiv...,Excellent. Good: staff location Bad: we di...
1,Expedia,,Of course the views are to die for! Room was v...,Of course the views are to die for! Room was v...
2,Ctrip,Outstanding,Of course the views are to die for! Room was v...,Outstanding Of course the views are to die for...
3,Booking.com,exceptionnel,Good: vue incroyable piscine petit déjeuner,exceptionnel Good: vue incroyable piscine ...
4,NaN,,,
5,TripAdvisor,Magical,"This hotel is magical, in terms of its setting...","Magical This hotel is magical, in terms of its..."
6,Booking.com,bello pero conflictivo el tema de la habitación,Good: la Vista y ubicación Bad: aún no me h...,bello pero conflictivo el tema de la habitació...
7,TripAdvisor,"Best ,amazing,don’t. Miss it it’s a great hotel","Grate staf ,excellent service,marvellous place...","Best ,amazing,don’t. Miss it it’s a great hote..."
8,NaN,Perfect 4 day stay in Santorini,My wife and I stayed here for 4 days in early ...,Perfect 4 day stay in Santorini My wife and I ...
9,Booking.com,Fantastic!!,Good: We loved everything about our stay. The...,Fantastic!! Good: We loved everything about ou...

In [8]:
# Remove rows with no review text

gea = gea[gea["Review_Text"].str.strip() != ""].copy()
gea.reset_index(drop=True, inplace=True)

print("Reviews remaining:", len(gea))

Reviews remaining: 272

In [10]:
print("Language values:")
print(gea["Language"].value_counts(dropna=False))

Language values:
Language
English                  222
Portuguese                15
German                     7
Japanese                   6
French                     6
Spanish                    5
Language                   3
Chinese (Traditional)      3
Korean                     1
Italian                    1
Romanian                   1
Hebrew                     1
Swedish                    1
Name: count, dtype: int64

In [11]:
gea[gea["Language"]== "Language"][
    ["Review Site", "Review_Text", "Language"]
    ]

     Review Site          Review_Text  Language
53   Review Site  Review Title Review  Language
120  Review Site  Review Title Review  Language
206  Review Site  Review Title Review  Language

In [21]:
#Remove repeated header rows as they are not reviews 
gea = gea[gea["Language"] != "Language"].copy()
gea.reset_index(drop=True, inplace=True)

print("Reviews remaining:", len (gea))

Reviews remaining: 269

In [22]:
print(gea["Language"].value_counts())

Language
English                  222
Portuguese                15
German                     7
French                     6
Japanese                   6
Spanish                    5
Chinese (Traditional)      3
Korean                     1
Italian                    1
Romanian                   1
Hebrew                     1
Swedish                    1
Name: count, dtype: int64

In [23]:
# Remove repeated header rows

gea = gea[gea["Language"] != "Language"].copy()
gea.reset_index(drop=True, inplace=True)

print("Reviews remaining:", len(gea))
print(gea["Language"].value_counts())

Reviews remaining: 269
Language
English                  222
Portuguese                15
German                     7
French                     6
Japanese                   6
Spanish                    5
Chinese (Traditional)      3
Korean                     1
Italian                    1
Romanian                   1
Hebrew                     1
Swedish                    1
Name: count, dtype: int64

In [24]:
# Check duplicate reviews

print("Total reviews:", len(gea))
print("Duplicate reviews:", gea["Review_Text"].duplicated().sum())

Total reviews: 269
Duplicate reviews: 20

In [27]:
#Removing duplicate reviews 
gea = gea.drop_duplicates(
    subset=["Review_Text"],
    keep="first").copy()

gea.reset_index(drop=True, inplace=True)
print("Reviews after removing duplicates:", len(gea))

Reviews after removing duplicates: 249

In [35]:
#Checking short reviews
gea["Review_Length"] = gea["Review_Text"].astype(str).str.strip().str.len()
gea["Short_Review"] = gea["Review_Length"] <10

In [37]:
print("Total reviews:", len(gea))
print("Short reviews:", gea["Short_Review"].sum())

Total reviews: 249
Short reviews: 4

In [39]:
#Creating English dataset for NLP
gea_english = gea[
    gea["Language"] == "English"
    ].copy()
print("All reviews:", len(gea))
print("English reviews:", len(gea_english))
print("Other languages:", len(gea) - len(gea_english))

All reviews: 249
English reviews: 202
Other languages: 47

In [43]:
import re

gea_english["Clean_Text"] = (
gea_english["Review_Text"]
.astype(str)
.str.lower()
.str.replace(r"http\S+|www\S+", "", regex=True)
.str.replace(r"[^a-z\s]", " ", regex=True)
.str.replace(r"\s+", " ", regex=True)
.str.strip()
)

gea_english[["Review_Text", "Clean_Text"]].head(10)

,Review_Text,Clean_Text
0,Excellent. Good: staff location Bad: we di...,excellent good staff location bad we didn t re...
1,Of course the views are to die for! Room was v...,of course the views are to die for room was ve...
2,Outstanding Of course the views are to die for...,outstanding of course the views are to die for...
4,"Magical This hotel is magical, in terms of its...",magical this hotel is magical in terms of its ...
6,"Best ,amazing,don’t. Miss it it’s a great hote...",best amazing don t miss it it s a great hotel ...
7,Perfect 4 day stay in Santorini My wife and I ...,perfect day stay in santorini my wife and i st...
8,Fantastic!! Good: We loved everything about ou...,fantastic good we loved everything about our s...
9,Magical stay Really lovely hotel. A place to r...,magical stay really lovely hotel a place to re...
10,Fantastic!! Good: We loved everything about ou...,fantastic good we loved everything about our s...
12,"Beautiful hotel , Breakfast was amazing, Great...",beautiful hotel breakfast was amazing great se...

In [44]:
import nltk
nltk.download("stopwords")
nltk.download("wordnet")

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

gea_english["Processed_Text"] = gea_english["Clean_Text"].apply(
lambda text: " ".join(
lemmatizer.lemmatize(word)
for word in text.split()
if word not in stop_words
)
)

gea_english[["Clean_Text", "Processed_Text"]].head(10)

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/8dff46cf-09d4-4d6f-9501-
[nltk_data]     4575fba38b61/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /home/8dff46cf-09d4-4d6f-9501-
[nltk_data]     4575fba38b61/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

,Clean_Text,Processed_Text
0,excellent good staff location bad we didn t re...,excellent good staff location bad receive hone...
1,of course the views are to die for room was ve...,course view die room clean staff accommodating...
2,outstanding of course the views are to die for...,outstanding course view die room clean staff a...
4,magical this hotel is magical in terms of its ...,magical hotel magical term setting quality foo...
6,best amazing don t miss it it s a great hotel ...,best amazing miss great hotel grate staf excel...
7,perfect day stay in santorini my wife and i st...,perfect day stay santorini wife stayed day ear...
8,fantastic good we loved everything about our s...,fantastic good loved everything stay staff fab...
9,magical stay really lovely hotel a place to re...,magical stay really lovely hotel place relax l...
10,fantastic good we loved everything about our s...,fantastic good loved everything stay staff fab...
12,beautiful hotel breakfast was amazing great se...,beautiful hotel breakfast amazing great servic...

In [45]:
gea.to_excel("Gea_Preprocessed_All_Languages.xlsx", index=False)

gea_english.to_excel("Gea_Preprocessed_English.xlsx", index=False)

print("Files saved!")

Files saved!